apiVersion: v1
kind: Pod
metadata:
  name: multi 
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - image: nginx
    name: web-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: ftp-container
    image: fauria/vsftpd
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    env:
    - name: FTP_USER
      value: admin
    - name: FTP_PASS
      value: password
