apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: myapp
  type: LoadBalancer
